Fixes task deletion and adds completion toggle functionality
Tepanyega/to_doList pull request #1
Opened 2024-11-06 12:28 UTC by Tepanyega

Fixed Task Deletion:
Updated the task deletion endpoint to properly remove tasks from the array.
Tasks are now correctly deleted when the delete icon is clicked.

Added Completion Toggle:
Implemented a feature to mark tasks as completed. When a user clicks the Complete button, the task text is crossed out (strikethrough) to indicate completion.

Why this change is needed:
The task deletion was not functioning correctly in the previous version due to a bug in the route handling.
The addition of a completion toggle enhances the user experience, allowing users to track completed tasks visually.

2024-11-08 07:06 UTC, bokangkhumalo requested changes
Hi @Tepanyega,

Great work on implementing the core functionality! I have a few suggestions that could make the code easier to understand and maintain:

Add Comments for Key Sections: The absence of comments makes some parts of the code difficult to follow, particularly around complex logic and data processing steps. Brief comments summarizing each key section would enhance readability.

Clarify Function and Variable Names: Some functions and variables (e.g., doTask()) could be renamed to better reflect their specific purposes. This can improve understanding without needing additional comments.

Add Documentation or README: A short README or module-level docstring explaining the project structure and the role of each module would be very helpful for future contributors and reviewers.

2024-11-08 07:06 UTC, bokangkhumalo commented on README.md
> +```
Hi @Tepanyega 

Thank you for your contributions! I wanted to point out that your clone link says yourusername, please fix this omission

2024-11-08 10:01 UTC, Tepanyega commented on README.md
> +```
Hi @bokangkhumalo,

Sorted, Thank you.

2024-11-08 12:12 UTC, alphineandre requested changes
I think if u can make those changes it will be complete

2024-11-08 12:12 UTC, alphineandre commented on public/css/style.css
I like everything so far but i would say improve the CSS, at this moment in time it looks a bit like a default webpage give it a bit more color and try separating the current tasks and the finished tasks.

2024-11-08 12:14 UTC, bokangkhumalo approved these changes

2024-11-08 12:14 UTC, bokangkhumalo commented on README.md
> +```
HI @Tepanyega,

Glad to see you implement the changes! happy coding

2024-11-08 12:17 UTC, bokangkhumalo commented on README.md
> +```
g

2024-11-08 12:26 UTC, KhanyiCodes approved these changes

2024-11-08 12:30 UTC, bokangkhumalo approved these changes

2024-11-08 12:30 UTC, bokangkhumalo commented on README.md
> +git clone https://github.com/Tepanyega/to_doList.git
Hi @Tepanyega, Glad to see your changes. Happy coding! ;)

2024-11-08 13:58 UTC, Tepanyega commented on public/css/style.css
Thank you, 
I made some changes on the design, you can check it out.

2024-11-12 09:10 UTC, KhanyiCodes commented on public/css/style.css
Thank you for your feedback! I'm really glad to hear you're liking the app so far. I totally agree that the CSS could use some improvement to make it feel more polished and visually appealing. To enhance the design, I’ve decided to incorporate neon colors into the layout. These bright, vibrant hues will add more energy and create a more dynamic, engaging interface.

For separating current tasks from finished tasks, I think your suggestion is spot-on. I'll work on creating a clearer visual distinction between them. Here’s what I’m thinking:

Neon-colored highlights or labels to differentiate tasks based on their status.
A subtle neon border or background shade for completed tasks to make them stand out.
Interactive elements like buttons or status indicators that use neon tones to create a modern, eye-catching effect.
I’ll be sure to balance the neon elements so it doesn’t overwhelm the user, but instead creates a sleek, vibrant, and functional experience. Once I’ve made these adjustments, I'll share an updated version for your feedback.

Thanks again for the great suggestions! Let me know if there’s anything else you’d like me to focus on, and I’ll keep you posted on the progress.

New CSS:
![image](https://github.com/user-attachments/assets/d8db84d7-e469-465c-b5ee-a9e953d08f74)

2024-11-12 09:27 UTC, alphineandre approved these changes
Great work its looks great now

2024-11-12 12:19 UTC, KhanyiCodes approved these changes

2024-11-12 12:21 UTC, KhanyiCodes approved these changes

2024-11-13 06:41 UTC, PhodzoW0l7 approved these changes

2024-11-13 11:37 UTC, JKRakuba approved these changes

2024-11-13 11:38 UTC, merged